### ISSUE TITLE
Charset missing in Content-Type header

### ISSUE THREAD

**Issue by bratkartoffel** [tafli/MeritServer#2]
As there is no charset specified in the Content-Type header, browsers display german umlauts as hieroglyphs.
Please change the Content-Type header to something like "Content-Type: application/json;charset=utf-8"

**Comment by tafli** [comment]
According to RFC 4627 (https://tools.ietf.org/html/rfc4627), the default encoding of application/json is UTF8. So content-type application/json is enough.
I did some testing with browser and it depends on your browser. Firefox does it wrong and has several bug issues open: https://bugzilla.mozilla.org/show_bug.cgi?id=741776.
