### ISSUE TITLE
Support query parameters for GET transactions

### ISSUE THREAD

**Issue by MartinGantenbein** [tafli/MeritServer#6]
GET transactions should support optional query parameters
- booked (true/false)
- sender (id)
- receiver (id)
- from (timestamp)
- to (timestamp)

**Comment by tafli** [comment]
implemented parameters:
- booked
- from (sender-id)
- to (receiver-id)
- fromTS (timestamp) like 2017-01-25T12:00:00
- toTS (timestamp) like 2017-01-25T12:00:00
