### ISSUE TITLE
Payday only adds balance to one user

### ISSUE THREAD

**Issue by MartinGantenbein** [tafli/MeritServer#8]
On todays' payday, the merits of only one user got added to the balance. All other users' balances remained 0...

Hints that might help:
1. The user with the correct balance is the first user in `users.json`
2. The payday POST request contained a JSON body where "to" was set to the user id with the correct balance

**Comment by tafli** [comment]
I don't understand your hint 2. What exactly was the request you sent that causes the error?

**Comment by MartinGantenbein** [comment]
I sent a payday request with a merits body

**Comment by tafli** [comment]
Found the problem and made a fix.
